Class {
	#name : #BSModel,
	#superclass : #CMAbstractModel,
	#instVars : [
		'theHabitatTypes',
		'thePromeneurGuides',
		'thePromeneurSeuls',
		'thePhoques',
		'numberOfRows',
		'numberOfColumns'
	],
	#category : #'Baie de Somme-Model'
}

{ #category : #'- probes' }
BSModel class >> colorOfProbe_numberOfPromeneurGuides [
  ^ (Color r: 1.0 g: 0.20234604105571846 b: 0.0 alpha: 1.0)
]

{ #category : #'simulation settings' }
BSModel class >> defaultInit [

	^ #simpleEnvironment
]

{ #category : #accessing }
BSModel class >> initialNumberOfPromeneurGuides [

	^10
]

{ #category : #accessing }
BSModel class >> initialNumberOfPromeneurSeuls [

	^2
]

{ #category : #'as yet unclassified' }
BSModel >> habitatTypeMatrix [

	| matrix |
	
	matrix := #(
		(2 2 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0)
		(2 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 2 2 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)).
		
	(matrix size = numberOfRows and: [ matrix allSatisfy: [ :row | row size = numberOfColumns ] ])
		ifFalse: [ self error: 'Matrix has the wrong dimensions' ].
		
	^ matrix
]

{ #category : #initialization }
BSModel >> initialize [ 

	super initialize.
	
	numberOfRows := 30.
	numberOfColumns:= 30.
	
	thePromeneurGuides := OrderedCollection new.
	thePromeneurSeuls := OrderedCollection new.
	thePhoques := OrderedCollection new.
	theHabitatTypes := OrderedCollection new.
]

{ #category : #'init entities' }
BSModel >> initializeAgents [ 

	self
		createN: "self class initialNumberOfPromeneurGuides" 5
		randomlyLocatedAloneEntities: BSPromeneurGuide.
		
	self
		createN: "self class initialNumberOfPromeneurSeuls" 7
		randomlyLocatedAloneEntities: BSPromeneurSeul.
		
	self createN: 20 randomlyLocatedEntities: BSPhoque.
]

{ #category : #initialization }
BSModel >> initializeHabitatTypeFromMatrix [

	| matrixCellValue modelCell |
	1 to: numberOfRows do: [ :i | 
		1 to: numberOfColumns do: [ :j | 
			matrixCellValue := (self habitatTypeMatrix at: i) at: j.
			modelCell := self pickCellAt: j @ i.
			matrixCellValue = 0 ifTrue: [ modelCell type: 'Sea' ].
			matrixCellValue = 1 ifTrue: [ modelCell type: 'Land' ].
			matrixCellValue = 2 ifTrue: [ modelCell type: 'Home' ].
			] ]
]

{ #category : #initialization }
BSModel >> initializeLegalStatusFromMatrix [

	| matrixCellValue modelCell |
	1 to: numberOfRows do: [ :i | 
		1 to: numberOfColumns do: [ :j | 
			matrixCellValue := (self legalStatusMatrix at: i) at: j.
			modelCell := self pickCellAt: j @ i.
			matrixCellValue = 0 ifTrue: [ modelCell legalStatus:  'Public' ].
			matrixCellValue = 1 ifTrue: [ modelCell legalStatus:  'Private' ].
			] ]
]

{ #category : #'as yet unclassified' }
BSModel >> legalStatusMatrix [

	| matrix |
	
	matrix := #(
		(1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
		(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)).
		
	(matrix size = numberOfRows and: [ matrix allSatisfy: [ :row | row size = numberOfColumns ] ])
		ifFalse: [ self error: 'Matrix has the wrong dimensions' ].
		
	^ matrix
]

{ #category : #probes }
BSModel >> numberOfPromeneurGuides [

	<probe>
	^ self thePromeneurGuides size
]

{ #category : #init }
BSModel >> simpleEnvironment [

	self
		createGridLines: numberOfRows
		columns: numberOfColumns
		neighbourhood: 8
		closed: false.

	"self theHabitatTypes do: [ :each | each initializeWithRandomHabitat ]."
	"(self theHabitatTypes at: 1) type: 'Home'."
	self initializeHabitatTypeFromMatrix.
	self initializeLegalStatusFromMatrix.

	self
		initializeAgents;
		displayPov: #povHabitatType of: BSHabitatCell;
		displayPov: #defaultPOV of:  BSPromeneur;
		displayPov: #defaultPOV of: BSPhoque.
]

{ #category : #control }
BSModel >> step: anObject [

	self askRandom: BSPromeneur toDo: #step 
]

{ #category : #accessing }
BSModel >> theHabitatTypes [
	<getterFor: #BSHabitatCell>

	^ theHabitatTypes
]

{ #category : #accessing }
BSModel >> theHabitatTypes: anObject [

	theHabitatTypes := anObject
]

{ #category : #accessing }
BSModel >> thePhoques [
<getterFor: #BSPhoque >
	^ thePhoques
]

{ #category : #accessing }
BSModel >> thePhoques: anObject [

	thePhoques := anObject
]

{ #category : #accessing }
BSModel >> thePromeneurGuides [
	<getterFor: #BSPromeneurGuide>	

	^ thePromeneurGuides
]

{ #category : #accessing }
BSModel >> thePromeneurGuides: anObject [

	thePromeneurGuides := anObject
]

{ #category : #accessing }
BSModel >> thePromeneurSeuls [
	<getterFor: #BSPromeneurSeul>

	^ thePromeneurSeuls
]

{ #category : #accessing }
BSModel >> thePromeneurSeuls: anObject [

	thePromeneurSeuls := anObject
]

{ #category : #probes }
BSModel >> totalSatisfaction [

	<probe>
	^ (self thePromeneurGuides sum: [ :each | each satisfaction ]) + (self thePromeneurSeuls sum: [ :each | each satisfaction ])
]
